language: node_js
node_js:
  - "7"
env:
  - PLAYBOOK=001-001/playbook
  - PLAYBOOK=001-002/playbook
  - PLAYBOOK=001-003/playbook
  - PLAYBOOK=002-001/playbook
install:
  - npm install --global @angular/cli
  - npm install --global typescript
  - npm install --global webpack
  - npm install
before_script:
  - tsc -p tsconfig.json
script:
  - "node playbooks/$PLAYBOOK"
