language: node_js
node_js:
  - "7"
before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
install:
  - yarn global add @angular/cli
script:
  - bash code-examples/001-003/ci.sh
